/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * JSON Schema для состояния спиральной секции (SpiralSectionState), расширяющая базовую схему секции
 */
export type SpiralSectionState = BaseSectionState & {
  Lift: LiftState;
  DeliveryBox: DeliveryBoxState;
  [k: string]: unknown;
};

/**
 * JSON Schema для глобального дерева состояний вендингового аппарата (States)
 */
export interface GlobalStates {
  /**
   * Уникальное имя вендингового аппарата
   */
  Name: string;
  /**
   * Дата и время введения аппарата в эксплуатацию
   */
  StartDate: string;
  Command?: COMMAND_STATE;
  Status: MACHINE_STATUS;
  Mode: GLOBAL_MACHINE_STATE;
  Resource?: RESOURCE_STATE;
  Mains: MainsState;
  Env: EnvState;
  /**
   * Список флагов состояния шин электропитания
   */
  Bus?: BusState[];
  Net: NetState;
  /**
   * Список флагов состояния источников питания (ИП)
   */
  PSU: PsuState[];
  /**
   * Список состояний секций вендингового аппарата
   */
  Sections: (SpiralSectionState | BaseSectionState)[];
}
/**
 * Флаги состояния электропитания сети
 */
export interface MainsState {
  Voltage: MEAS_STATE;
}
/**
 * Флаги состояния датчиков окружающей среды
 */
export interface EnvState {
  Temp: MEAS_STATE;
  Hum: MEAS_STATE;
}
/**
 * Флаги состояния шины электропитания
 */
export interface BusState {
  Voltage: MEAS_STATE;
  Current: BUS_CURRENT_STATE;
}
/**
 * Состояния сетевых служб и компонентов автомата
 */
export interface NetState {
  /**
   * Агрегированные показатели сетевых подсистем
   */
  Summary: {
    Apparatus: NET_SUMMARY_STATE;
    LAN: NET_SUMMARY_STATE;
    CoreServices: NET_SUMMARY_STATE;
    Hubs: NET_SUMMARY_STATE;
    Cameras: NET_SUMMARY_STATE;
    Logging: NET_SUMMARY_STATE;
  };
  /**
   * Статусы сетевых устройств
   */
  Device: {
    Router: NET_DEVICE_STATE;
    SW_PoE: NET_DEVICE_STATE;
    Hub_Low: NET_DEVICE_STATE;
    Hub_Mid: NET_DEVICE_STATE;
    Hub_Hi: NET_DEVICE_STATE;
    Cam1: NET_DEVICE_STATE;
    Cam2: NET_DEVICE_STATE;
  };
  /**
   * Статусы физических линков
   */
  Link: {
    Router_Hub_Low: NET_LINK_STATE;
    Router_Hub_Mid: NET_LINK_STATE;
    Router_Hub_Hi: NET_LINK_STATE;
    Router_SW_PoE: NET_LINK_STATE;
    SW_PoE_Cam1: NET_LINK_STATE;
    SW_PoE_Cam2: NET_LINK_STATE;
  };
  /**
   * Состояние IP-адресации, ARP и шлюза
   */
  IP: {
    Plan: NET_IP_STATE;
    ARP: NET_ARP_STATE;
    Gateway: NET_GATEWAY_STATE;
  };
  /**
   * Состояние сетевых маршрутов
   */
  Route: {
    Local: NET_ROUTE_STATE;
    Internet: NET_ROUTE_STATE;
    VPN: NET_ROUTE_STATE;
  };
  /**
   * Показатели качества связи
   */
  Quality: {
    LAN: NET_QUALITY_STATE;
  };
  /**
   * Состояние питания PoE
   */
  PoE: {
    SW_PoE: NET_POE_STATE;
    Cam1: NET_POE_STATE;
    Cam2: NET_POE_STATE;
  };
  /**
   * Состояния сервисов видеокамер
   */
  Camera: {
    Cam1_HTTP: NET_CAMERA_SERVICE_STATE;
    Cam2_HTTP: NET_CAMERA_SERVICE_STATE;
    Cam1_RTSP: NET_CAMERA_SERVICE_STATE;
    Cam2_RTSP: NET_CAMERA_SERVICE_STATE;
  };
  /**
   * Состояния службы времени NTP
   */
  NTP: {
    Server: NET_NTP_STATE;
    Hub_Low: NET_NTP_STATE;
    Hub_Mid: NET_NTP_STATE;
    Hub_Hi: NET_NTP_STATE;
    Cameras: NET_NTP_STATE;
  };
  /**
   * Состояние службы разрешение имён DNS
   */
  DNS: {
    Server: NET_DNS_STATE;
    LocalRecords: NET_DNS_STATE;
    HubsResolver: NET_DNS_STATE;
  };
  /**
   * Состояние службы сообщений MQTT
   */
  MQTT: {
    Server: NET_MQTT_STATE;
    Clients: NET_MQTT_STATE;
    Retained: NET_MQTT_STATE;
  };
  /**
   * Состояние оперативной БД Redis
   */
  Redis: {
    Server: NET_DB_SERVICE_STATE;
  };
  /**
   * Состояние долгосрочной БД MongoDB
   */
  MongoDB: {
    Server: NET_DB_SERVICE_STATE;
  };
  /**
   * Состояние службы Node-RED на хабах
   */
  NodeRED: {
    Hub_Low: NET_NODERED_STATE;
    Hub_Mid: NET_NODERED_STATE;
    Hub_Hi: NET_NODERED_STATE;
  };
  /**
   * Состояние центрального сервиса логирования Graylog
   */
  Graylog: {
    Server: NET_GRAYLOG_STATE;
    Delivery_Hubs: NET_GRAYLOG_STATE;
    Delivery_Network: NET_GRAYLOG_STATE;
  };
  /**
   * Показатели сетевой безопасности
   */
  Security: {
    UnknownDevice: NET_SECURITY_STATE;
    OpenPorts: NET_SECURITY_STATE;
    Firewall: NET_SECURITY_STATE;
    Credentials: NET_SECURITY_STATE;
  };
  /**
   * Режимы деградации сетевой инфраструктуры
   */
  Mode: {
    Degraded: NET_DEGRADED_STATE;
  };
}
/**
 * Флаги состояния источника питания (ИП)
 */
export interface PsuState {
  VoltageIn: MEAS_STATE;
  VoltageOut: MEAS_STATE;
  CurrentOut: BUS_CURRENT_STATE;
  Temp: MEAS_STATE;
  ShortCircuit: AVAILABLE_STATE;
  Enabled: AVAILABLE_STATE;
  Resource: AVAILABLE_STATE;
}
/**
 * JSON Schema для базового состояния секции (BaseSectionState)
 */
export interface BaseSectionState {
  /**
   * Наименование секции (например, 'spiral', 'postomat')
   */
  Name?: string;
  IsAvailable: AVAILABLE_STATE1;
  Door: DOOR_STATE;
  Action: SECTION_ACTION;
  Status: SECTION_STATUS;
  /**
   * Массив состояний строк (полок) секции
   */
  Rows: LINE_STATE[];
  /**
   * Массив состояний столбцов секции
   */
  Cols: LINE_STATE[];
  /**
   * Массив состояний ячеек секции
   */
  Cells: TYPE_CELL[];
  /**
   * Словарь состояний модулей ввода-вывода (IO)
   */
  IO: {
    [k: string]: TYPE_IO;
  };
  [k: string]: unknown;
}
/**
 * Объект состояния ячейки секции (Status, Action, Resource)
 */
export interface TYPE_CELL {
  Status: CELL_STATE;
  Action: CELL_ACTION;
  Resource: AVAILABLE_STATE1;
}
/**
 * Объект состояния модуля ввода-вывода (IO)
 */
export interface TYPE_IO {
  Status: IO_STATE;
  /**
   * Массив состояний цифровых выходов DO
   */
  DO: IO_PORT_STATE[];
  /**
   * Массив состояний цифровых входов DI
   */
  DI: IO_PORT_STATE[];
  Resource: AVAILABLE_STATE1;
}
/**
 * Состояние лифта спиральной секции (Status, Resource)
 */
export interface LiftState {
  Status: LIFT_STATE;
  Resource: AVAILABLE_STATE1;
}
/**
 * Состояние лючка выдачи спиральной секции (Status, Resource)
 */
export interface DeliveryBoxState {
  Status: DELIVERY_BOX_STATE;
  Resource: AVAILABLE_STATE1;
}

/**
 * Состояние выполнения команд (IDLE - ожидание команды, COMMAND - выполнение команды, BLOCKED - заблокировано)
 */
export enum COMMAND_STATE {
  IDLE = "IDLE",
  COMMAND = "COMMAND",
  BLOCKED = "BLOCKED"
}
/**
 * Глобальный статус работоспособности аппарата (OK - штатный режим, WARNING - режим частичной работоспособности, ERROR - нештатный режим)
 */
export enum MACHINE_STATUS {
  OK = "OK",
  WARNING = "WARNING",
  ERROR = "ERROR"
}
/**
 * Глобальные режимы работы аппарата (OK - штатный режим, SERVICE - техническое обслуживание, DEPLOY - обновление прошивки, RESTART - режим перезапуска, STOP - режим останова)
 */
export enum GLOBAL_MACHINE_STATE {
  OK = "OK",
  SERVICE = "SERVICE",
  DEPLOY = "DEPLOY",
  RESTART = "RESTART",
  STOP = "STOP"
}
/**
 * Общее состояние моторесурса аппарата (OK - в допуске, WARNING - требуется обслуживание, ERROR - моторесурс исчерпан)
 */
export enum RESOURCE_STATE {
  OK = "OK",
  WARNING = "WARNING",
  ERROR = "ERROR"
}
/**
 * Статус измерений (OK - значение в норме, ERR_HIGH - значение повышено, ERR_LOW - значение понижено)
 */
export enum MEAS_STATE {
  OK = "OK",
  ERR_HIGH = "ERR_HIGH",
  ERR_LOW = "ERR_LOW"
}
/**
 * Статус тока шины или источника питания (OK - в норме, ERR_HIGH - повышенный ток)
 */
export enum BUS_CURRENT_STATE {
  OK = "OK",
  ERR_HIGH = "ERR_HIGH"
}
/**
 * Агрегированный статус сетевых сервисов и узлов (READY - готов, OK - в норме, DEGRADED - частичная деградация, FAIL - сбой, OFFLINE - отключено, UNKNOWN - нет данных)
 */
export enum NET_SUMMARY_STATE {
  READY = "READY",
  OK = "OK",
  DEGRADED = "DEGRADED",
  FAIL = "FAIL",
  OFFLINE = "OFFLINE",
  UNKNOWN = "UNKNOWN"
}
/**
 * Статус сетевого устройства (ONLINE - доступен, OFFLINE - недоступен, ERR_API - ошибка API, ERR_CONFIG - ошибка конфигурации, ERR_MANAGEMENT - нет доступа к управлению, ERR_NO_LINK - потерян линк, ERR_NO_IP - нет IP, ERR_SERVICE_ACCESS - нет доступа к сервисам, ERR_NO_POE - нет PoE питания, ERR_AUTH - ошибка авторизации, UNKNOWN - нет данных)
 */
export enum NET_DEVICE_STATE {
  ONLINE = "ONLINE",
  OFFLINE = "OFFLINE",
  ERR_API = "ERR_API",
  ERR_CONFIG = "ERR_CONFIG",
  ERR_MANAGEMENT = "ERR_MANAGEMENT",
  ERR_NO_LINK = "ERR_NO_LINK",
  ERR_NO_IP = "ERR_NO_IP",
  ERR_SERVICE_ACCESS = "ERR_SERVICE_ACCESS",
  ERR_NO_POE = "ERR_NO_POE",
  ERR_AUTH = "ERR_AUTH",
  UNKNOWN = "UNKNOWN"
}
/**
 * Статус физического сетевого линка (UP - поднят, DOWN - отсутствует, ERR_SPEED - несоответствие скорости, ERR_ERRORS - ошибки на порту/CRC, UNKNOWN - нет данных)
 */
export enum NET_LINK_STATE {
  UP = "UP",
  DOWN = "DOWN",
  ERR_SPEED = "ERR_SPEED",
  ERR_ERRORS = "ERR_ERRORS",
  UNKNOWN = "UNKNOWN"
}
/**
 * Статус IP-адресации (OK - в норме, ERR_NO_IP - нет IP, ERR_WRONG_IP - неверный IP, ERR_DUPLICATE_IP - дубликат IP, UNKNOWN - нет данных)
 */
export enum NET_IP_STATE {
  OK = "OK",
  ERR_NO_IP = "ERR_NO_IP",
  ERR_WRONG_IP = "ERR_WRONG_IP",
  ERR_DUPLICATE_IP = "ERR_DUPLICATE_IP",
  UNKNOWN = "UNKNOWN"
}
/**
 * Статус ARP-таблицы (OK - в норме, ERR_MAC_CHANGED - изменился MAC, ERR_MAC_DUPLICATE - дубликат MAC, ERR_MISSING_ARP - нет записи ARP, UNKNOWN - нет данных)
 */
export enum NET_ARP_STATE {
  OK = "OK",
  ERR_MAC_CHANGED = "ERR_MAC_CHANGED",
  ERR_MAC_DUPLICATE = "ERR_MAC_DUPLICATE",
  ERR_MISSING_ARP = "ERR_MISSING_ARP",
  UNKNOWN = "UNKNOWN"
}
/**
 * Статус сетевого шлюза (OK - доступен, ERR_NO_GATEWAY - шлюз не задан, ERR_GATEWAY_UNREACHABLE - шлюз недоступен, UNKNOWN - нет данных)
 */
export enum NET_GATEWAY_STATE {
  OK = "OK",
  ERR_NO_GATEWAY = "ERR_NO_GATEWAY",
  ERR_GATEWAY_UNREACHABLE = "ERR_GATEWAY_UNREACHABLE",
  UNKNOWN = "UNKNOWN"
}
/**
 * Статус маршрута (OK - исправен, OFFLINE - отключен, DEGRADED - сбои, FAIL - недоступен, NOT_REQUIRED - не требуется, UNKNOWN - нет данных)
 */
export enum NET_ROUTE_STATE {
  OK = "OK",
  OFFLINE = "OFFLINE",
  DEGRADED = "DEGRADED",
  FAIL = "FAIL",
  NOT_REQUIRED = "NOT_REQUIRED",
  UNKNOWN = "UNKNOWN"
}
/**
 * Статус качества связи (OK - в норме, WARN_LATENCY - задержка, WARN_JITTER - джиттер, WARN_PACKET_LOSS - потери пакетов, FAIL_STORM - сетевой шторм, FAIL_MAC_FLAP - флэппинг MAC, UNKNOWN - нет данных)
 */
export enum NET_QUALITY_STATE {
  OK = "OK",
  WARN_LATENCY = "WARN_LATENCY",
  WARN_JITTER = "WARN_JITTER",
  WARN_PACKET_LOSS = "WARN_PACKET_LOSS",
  FAIL_STORM = "FAIL_STORM",
  FAIL_MAC_FLAP = "FAIL_MAC_FLAP",
  UNKNOWN = "UNKNOWN"
}
/**
 * Статус PoE питания (OK - в норме, OFF - отключен, WARN_BUDGET - порог бюджета, ERR_BUDGET - превышение бюджета, ERR_MANAGEMENT - ошибка управления, ERR_POWER_LOW - пониженное потребление, ERR_POWER_HIGH - повышенное потребление, ERR_PORT - ошибка порта, UNKNOWN - нет данных)
 */
export enum NET_POE_STATE {
  OK = "OK",
  OFF = "OFF",
  WARN_BUDGET = "WARN_BUDGET",
  ERR_BUDGET = "ERR_BUDGET",
  ERR_MANAGEMENT = "ERR_MANAGEMENT",
  ERR_POWER_LOW = "ERR_POWER_LOW",
  ERR_POWER_HIGH = "ERR_POWER_HIGH",
  ERR_PORT = "ERR_PORT",
  UNKNOWN = "UNKNOWN"
}
/**
 * Статус сервиса IP-камеры (OK - отвечает, ERR_CONNECT - ошибка подключения, ERR_AUTH - ошибка авторизации, ERR_TIMEOUT - таймаут ответа, ERR_NO_STREAM - нет видеопотока, UNKNOWN - нет данных)
 */
export enum NET_CAMERA_SERVICE_STATE {
  OK = "OK",
  ERR_CONNECT = "ERR_CONNECT",
  ERR_AUTH = "ERR_AUTH",
  ERR_TIMEOUT = "ERR_TIMEOUT",
  ERR_NO_STREAM = "ERR_NO_STREAM",
  UNKNOWN = "UNKNOWN"
}
/**
 * Статус синхронизации времени NTP (OK - отвечает, SYNC - синхронизирован, UNSYNC - рассинхронизирован, ERR_NO_RESPONSE - нет ответа, ERR_BAD_TIME - некорректное время, ERR_STRATUM - неверный stratum, ERR_OFFSET - смещение времени, ERR_NO_SERVER - нет сервера, WARN_OFFSET - предупреждение по смещению, UNKNOWN - нет данных)
 */
export enum NET_NTP_STATE {
  OK = "OK",
  SYNC = "SYNC",
  UNSYNC = "UNSYNC",
  ERR_NO_RESPONSE = "ERR_NO_RESPONSE",
  ERR_BAD_TIME = "ERR_BAD_TIME",
  ERR_STRATUM = "ERR_STRATUM",
  ERR_OFFSET = "ERR_OFFSET",
  ERR_NO_SERVER = "ERR_NO_SERVER",
  WARN_OFFSET = "WARN_OFFSET",
  UNKNOWN = "UNKNOWN"
}
/**
 * Статус службы DNS (OK - в норме, ERR_NO_RESPONSE - нет ответа, ERR_BAD_RESPONSE - некорректный ответ, ERR_MISSING_RECORD - нет записи, ERR_WRONG_RECORD - ошибочная запись, ERR_BAD_RESOLVER - ошибка резолвера, ERR_LOCAL_RESOLVE - ошибка локального разрешения, ERR_EXTERNAL_RESOLVE - ошибка внешнего разрешения, UNKNOWN - нет данных)
 */
export enum NET_DNS_STATE {
  OK = "OK",
  ERR_NO_RESPONSE = "ERR_NO_RESPONSE",
  ERR_BAD_RESPONSE = "ERR_BAD_RESPONSE",
  ERR_MISSING_RECORD = "ERR_MISSING_RECORD",
  ERR_WRONG_RECORD = "ERR_WRONG_RECORD",
  ERR_BAD_RESOLVER = "ERR_BAD_RESOLVER",
  ERR_LOCAL_RESOLVE = "ERR_LOCAL_RESOLVE",
  ERR_EXTERNAL_RESOLVE = "ERR_EXTERNAL_RESOLVE",
  UNKNOWN = "UNKNOWN"
}
/**
 * Статус брокера MQTT (OK - доступен и работает, ERR_TCP - нет TCP подключения, ERR_AUTH - ошибка авторизации, ERR_PUBSUB - ошибка Pub/Sub, ERR_LATENCY - высокая задержка, ERR_HUB_LOW/MID/HI - ошибки хабов, ERR_RECONNECTS - частые переподключения, WARN_STALE - устаревшие данные, ERR_INVALID - невалидные данные, UNKNOWN - нет данных)
 */
export enum NET_MQTT_STATE {
  OK = "OK",
  ERR_TCP = "ERR_TCP",
  ERR_AUTH = "ERR_AUTH",
  ERR_PUBSUB = "ERR_PUBSUB",
  ERR_LATENCY = "ERR_LATENCY",
  ERR_HUB_LOW = "ERR_HUB_LOW",
  ERR_HUB_MID = "ERR_HUB_MID",
  ERR_HUB_HI = "ERR_HUB_HI",
  ERR_RECONNECTS = "ERR_RECONNECTS",
  WARN_STALE = "WARN_STALE",
  ERR_INVALID = "ERR_INVALID",
  UNKNOWN = "UNKNOWN"
}
/**
 * Статус базы данных Redis/MongoDB (OK - доступна и выполняет команды, ERR_TCP - нет TCP подключения, ERR_AUTH - ошибка авторизации, ERR_COMMAND - ошибка выполнения команд, WARN_LATENCY - высокая задержка, WARN_MEMORY - лимит памяти, ERR_REPLICA - ошибка реплики, WARN_STORAGE - лимит диска, UNKNOWN - нет данных)
 */
export enum NET_DB_SERVICE_STATE {
  OK = "OK",
  ERR_TCP = "ERR_TCP",
  ERR_AUTH = "ERR_AUTH",
  ERR_COMMAND = "ERR_COMMAND",
  WARN_LATENCY = "WARN_LATENCY",
  WARN_MEMORY = "WARN_MEMORY",
  ERR_REPLICA = "ERR_REPLICA",
  WARN_STORAGE = "WARN_STORAGE",
  UNKNOWN = "UNKNOWN"
}
/**
 * Статус Node-RED (OK - доступен и потоки работают, ERR_HTTP - API недоступен, ERR_FLOWS - ошибка потоков, ERR_MQTT - нет подключения к MQTT, ERR_DEPLOY - ошибка деплоя, UNKNOWN - нет данных)
 */
export enum NET_NODERED_STATE {
  OK = "OK",
  ERR_HTTP = "ERR_HTTP",
  ERR_FLOWS = "ERR_FLOWS",
  ERR_MQTT = "ERR_MQTT",
  ERR_DEPLOY = "ERR_DEPLOY",
  UNKNOWN = "UNKNOWN"
}
/**
 * Статус службы логирования Graylog (OK - доступен и пишет логи, ERR_HTTP - API недоступен, ERR_INPUTS - остановлены inputs, ERR_INDEXER - ошибка индексатора, WARN_QUEUE - растёт очередь, ERR_HUB_LOW/MID/HI - ошибки отправки хабов, ERR_ROUTER - ошибка роутера, ERR_SW_POE - ошибка коммутатора, DELAYED - задержка доставки, UNKNOWN - нет данных)
 */
export enum NET_GRAYLOG_STATE {
  OK = "OK",
  ERR_HTTP = "ERR_HTTP",
  ERR_INPUTS = "ERR_INPUTS",
  ERR_INDEXER = "ERR_INDEXER",
  WARN_QUEUE = "WARN_QUEUE",
  ERR_HUB_LOW = "ERR_HUB_LOW",
  ERR_HUB_MID = "ERR_HUB_MID",
  ERR_HUB_HI = "ERR_HUB_HI",
  ERR_ROUTER = "ERR_ROUTER",
  ERR_SW_POE = "ERR_SW_POE",
  DELAYED = "DELAYED",
  UNKNOWN = "UNKNOWN"
}
/**
 * Статус сетевой безопасности (OK - нарушений нет, DETECTED - обнаружена угроза, WARN_OPEN_PORT - открытый порт, FAIL_FORBIDDEN_SERVICE - запрещенная служба, ERR_RULE_MISSING - нет правила, ERR_RULE_DISABLED - правило отключено, ERR_POLICY - нарушение политики, FAIL_DEFAULT_PASSWORD - дефолтный пароль, WARN_EXPIRED_CERT - истёк сертификат, WARN_TLS_NAME - ошибка TLS имени, UNKNOWN - нет данных)
 */
export enum NET_SECURITY_STATE {
  OK = "OK",
  DETECTED = "DETECTED",
  WARN_OPEN_PORT = "WARN_OPEN_PORT",
  FAIL_FORBIDDEN_SERVICE = "FAIL_FORBIDDEN_SERVICE",
  ERR_RULE_MISSING = "ERR_RULE_MISSING",
  ERR_RULE_DISABLED = "ERR_RULE_DISABLED",
  ERR_POLICY = "ERR_POLICY",
  FAIL_DEFAULT_PASSWORD = "FAIL_DEFAULT_PASSWORD",
  WARN_EXPIRED_CERT = "WARN_EXPIRED_CERT",
  WARN_TLS_NAME = "WARN_TLS_NAME",
  UNKNOWN = "UNKNOWN"
}
/**
 * Режим деградации сети (NONE - нет деградации, CAMERAS_ONLY - только камеры, EXTERNAL_ONLY - только внешняя сеть, LOGGING_ONLY - только логи, SINGLE_HUB - один хаб, CORE_SERVICE - базовые сервисы, UNKNOWN - нет данных)
 */
export enum NET_DEGRADED_STATE {
  NONE = "NONE",
  CAMERAS_ONLY = "CAMERAS_ONLY",
  EXTERNAL_ONLY = "EXTERNAL_ONLY",
  LOGGING_ONLY = "LOGGING_ONLY",
  SINGLE_HUB = "SINGLE_HUB",
  CORE_SERVICE = "CORE_SERVICE",
  UNKNOWN = "UNKNOWN"
}
/**
 * Флаг доступности (YES - доступно/в норме, NO - недоступно/исчерпано)
 */
export enum AVAILABLE_STATE {
  YES = "YES",
  NO = "NO"
}
/**
 * Флаг доступности (YES - доступно/в норме, NO - недоступно/исчерпано)
 */
export enum AVAILABLE_STATE1 {
  YES = "YES",
  NO = "NO"
}
/**
 * Состояние сервисной двери секции (CLOSED - закрыта, OPEN - открыта)
 */
export enum DOOR_STATE {
  CLOSED = "CLOSED",
  OPEN = "OPEN"
}
/**
 * Действие секции (IDLE - секция простаивает, DISPENSE - секция занимается выдачей ТМЦ, LOADING - в секцию загружают ТМЦ)
 */
export enum SECTION_ACTION {
  IDLE = "IDLE",
  DISPENSE = "DISPENSE",
  LOADING = "LOADING"
}
/**
 * Статус готовности секции к командам ВУ (IDLE - ожидание команды ВУ, COMMAND - выполнение команды, BLOCKED - выполнение команд ВУ заблокировано)
 */
export enum SECTION_STATUS {
  IDLE = "IDLE",
  COMMAND = "COMMAND",
  BLOCKED = "BLOCKED"
}
/**
 * Состояние строки или столбца секции (OK - в норме, BLOCKED - заблокирован)
 */
export enum LINE_STATE {
  OK = "OK",
  BLOCKED = "BLOCKED"
}
/**
 * Флаги состояния ячейки (OK - штатно, OVERLOAD_I - повышенный ток, OVERLOAD_V - повышенное напряжение, BLOCKED - заблокирована, ERROR - ошибка, SERVICE - обслуживание, ERR_TAMPER - ошибка тампера, ERR_TAMPER_BAD_POS - некорректная позиция, ACTUATOR_SHORT_CIRCUIT - КЗ актуатора, ACTUATOR_NO_POWER - нет питания, ERR_MECHANICAL - механическая поломка)
 */
export enum CELL_STATE {
  OK = "OK",
  OVERLOAD_I = "OVERLOAD_I",
  OVERLOAD_V = "OVERLOAD_V",
  BLOCKED = "BLOCKED",
  ERROR = "ERROR",
  SERVICE = "SERVICE",
  ERR_TAMPER = "ERR_TAMPER",
  ERR_TAMPER_BAD_POS = "ERR_TAMPER_BAD_POS",
  ACTUATOR_SHORT_CIRCUIT = "ACTUATOR_SHORT_CIRCUIT",
  ACTUATOR_NO_POWER = "ACTUATOR_NO_POWER",
  ERR_MECHANICAL = "ERR_MECHANICAL"
}
/**
 * Флаги состояния действия ячейки (IDLE - закрыта/в ждущем режиме, ACTION - отрабатывает команду выдачи, OPEN - открыта, NOT_CLOSED - открыта слишком долго)
 */
export enum CELL_ACTION {
  IDLE = "IDLE",
  ACTION = "ACTION",
  OPEN = "OPEN",
  NOT_CLOSED = "NOT_CLOSED"
}
/**
 * Состояние модуля ввода-вывода (OK - в норме, ERR_NO_LINK - потеряно соединение с IO модулем)
 */
export enum IO_STATE {
  OK = "OK",
  ERR_NO_LINK = "ERR_NO_LINK"
}
/**
 * Состояние порта модуля ввода-вывода (OK - в норме, ERROR - порт повреждён)
 */
export enum IO_PORT_STATE {
  OK = "OK",
  ERROR = "ERROR"
}
/**
 * Флаги состояния лифта (OK - в норме, OVERLOAD - перегрузка, BLOCKED - недоступен, SHORT_CIRCUIT - короткое замыкание, NO_POWER - отсутствует питание, ERR_TAMPER - тампер вышел из строя, ERR_LEVEL - неисправен датчик уровня, ERR_MECHANICAL - механическая поломка)
 */
export enum LIFT_STATE {
  OK = "OK",
  OVERLOAD = "OVERLOAD",
  BLOCKED = "BLOCKED",
  SHORT_CIRCUIT = "SHORT_CIRCUIT",
  NO_POWER = "NO_POWER",
  ERR_TAMPER = "ERR_TAMPER",
  ERR_LEVEL = "ERR_LEVEL",
  ERR_MECHANICAL = "ERR_MECHANICAL"
}
/**
 * Флаги состояния лючка выдачи (OPENED - люк открыт, CLOSED - люк закрыт, ERR_MECHANICAL - механическая поломка)
 */
export enum DELIVERY_BOX_STATE {
  OPENED = "OPENED",
  CLOSED = "CLOSED",
  ERR_MECHANICAL = "ERR_MECHANICAL"
}
