/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * JSON Schema для мониторинга спиральной секции (SpiralSectionMonitoring), расширяющая базовую схему мониторинга секции
 */
export type SpiralSectionMonitoring = BaseSectionMonitoring & {
  Lift: LiftMonitoring;
  DeliveryBox: DeliveryBoxMonitoring;
  [k: string]: unknown;
};

/**
 * JSON Schema для системы глобального мониторинга аппарата (Monitoring)
 */
export interface GlobalMonitoring {
  /**
   * Глобальные переменные мониторинга аппарата
   */
  Global: {
    /**
     * Наработка аппарата, часов
     */
    Uptime: number;
    /**
     * Показатели сети электропитания
     */
    Power: {
      /**
       * Числовое значение входного сетевого напряжения, В
       */
      MainsVoltage: number;
      /**
       * Текущая потребляемая активная мощность, Вт
       */
      Consumption: number;
    };
    /**
     * Показатели потреблённой активной энергии
     */
    Energy: {
      /**
       * Потреблённая активная энергия за текущие сутки, кВт*ч
       */
      Day: number;
      /**
       * Потреблённая активная энергия за неделю, кВт*ч
       */
      Week: number;
      /**
       * Потреблённая активная энергия за месяц, кВт*ч
       */
      Month: number;
    };
    /**
     * Усредненные измерения датчиков окружающей среды
     */
    Env: {
      /**
       * Усреднённое значение температуры окружающей среды, °C
       */
      Temp: number;
      /**
       * Усреднённое значение влажности окружающей среды, %
       */
      Hum: number;
    };
  };
  /**
   * Переменные измерений шин электропитания
   */
  Bus: BusMonitoring[];
  /**
   * Переменные измерений и наработки источников питания (ИП)
   */
  PSU: PsuMonitoring[];
  /**
   * Переменные наработки и измерений секций аппарата
   */
  Sections: (SpiralSectionMonitoring | BaseSectionMonitoring)[];
}
/**
 * Параметры измерений шины электропитания
 */
export interface BusMonitoring {
  /**
   * Числовое значение напряжения на шине, В
   */
  Voltage: number;
  /**
   * Числовое значение тока на шине, А
   */
  Current: number;
}
/**
 * Переменные измерений и наработки источника питания (ИП)
 */
export interface PsuMonitoring {
  /**
   * Числовое значение входного напряжения, В
   */
  VoltageIn: number;
  /**
   * Числовое значение выходного напряжения, В
   */
  VoltageOut: number;
  /**
   * Числовое значение выходного тока, А
   */
  CurrentOut: number;
  /**
   * Числовое значение температуры ИП, °C
   */
  Temp: number;
  Uptime: PsuUptimeMonitoring;
}
/**
 * Показатели наработки источника питания (ИП)
 */
export interface PsuUptimeMonitoring {
  /**
   * Наработка ИП, часов
   */
  Hours: number;
  /**
   * Моторесурс работы ИП в штатном режиме, часов
   */
  Nominal: number;
  /**
   * Наработка в режиме перегрузки по току
   */
  OVCcount: number;
  /**
   * Наработка в режиме перегреве
   */
  OVTcount: number;
}
/**
 * JSON Schema для базового мониторинга секции (BaseSectionMonitoring)
 */
export interface BaseSectionMonitoring {
  /**
   * Имя секции (например, 'spiral', 'postomat')
   */
  Name: string;
  Uptime: ItemUptimeMonitoring;
  /**
   * Массив наработки строк (полок) секции
   */
  Rows?: {
    Uptime: ItemUptimeMonitoring;
  }[];
  /**
   * Массив наработки столбцов секции
   */
  Cols?: {
    Uptime: ItemUptimeMonitoring;
  }[];
  /**
   * Массив наработки ячеек секции
   */
  Cells: {
    Uptime: ItemUptimeMonitoring;
  }[];
  /**
   * Переменные наработки модулей ввода-вывода (IO)
   */
  IO?: {
    [k: string]: {
      Uptime: IoUptimeMonitoring;
    };
  };
  [k: string]: unknown;
}
/**
 * Показатели наработки конструктивного элемента (часы, циклы, типовой моторесурс)
 */
export interface ItemUptimeMonitoring {
  /**
   * Наработка, часов
   */
  Hours: number;
  /**
   * Наработка, циклов
   */
  Cycles: number;
  /**
   * Типовая наработка (номинальный моторесурс)
   */
  Nominal: number;
}
/**
 * Показатели наработки модуля ввода-вывода (IO)
 */
export interface IoUptimeMonitoring {
  /**
   * Наработка, часов
   */
  Hours: number;
  /**
   * Типичная наработка (номинальный моторесурс)
   */
  Nominal: number;
}
/**
 * Переменные наработки лифта секции
 */
export interface LiftMonitoring {
  Uptime: ItemUptimeMonitoring;
}
/**
 * Переменные наработки лючка выдачи
 */
export interface DeliveryBoxMonitoring {
  Uptime: DeliveryBoxUptimeMonitoring;
}
/**
 * Показатели наработки лючка выдачи
 */
export interface DeliveryBoxUptimeMonitoring {
  /**
   * Наработка, циклов
   */
  Cycles: number;
  /**
   * Типовая наработка (номинальный моторесурс)
   */
  Nominal: number;
}
