/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Каналы управления подсветкой секции
 */
export type LedChannelsConfig =
  | {
      /**
       * Канал управления подсветкой секции
       */
      Ctrl?: string;
    }
  | string;

/**
 * JSON Schema для аппаратной конфигурации вендингового аппарата (MachineConfig)
 */
export interface MachineConfig {
  Global: GlobalConfig;
  Monitoring: MonitoringConfig;
  Light: LightConfig;
  Power: PowerConfig;
  Env: EnvConfig;
  Net: NetConfig;
  Field: FieldBusesConfig;
  /**
   * Список конфигураций модулей ввода/вывода (IO)
   */
  IO: IoModuleConfig[];
  /**
   * Список конфигураций систем фотовидеоконтроля (камер)
   */
  Camera: CameraConfig[];
  /**
   * Список конфигураций секций аппарата
   */
  Sections: SectionConfig[];
}
/**
 * Глобальные параметры аппарата
 */
export interface GlobalConfig {
  /**
   * Уникальный идентификатор аппарата (UID)
   */
  ID: string;
  /**
   * Модель аппарата
   */
  Model: string;
  /**
   * Дата ввода в эксплуатацию (ГГГГ-ММ-ДД)
   */
  StartDate: string;
}
/**
 * Конфигурация параметров фонового мониторинга
 */
export interface MonitoringConfig {
  /**
   * Периодичность опроса и публикации мониторинга в миллисекундах
   */
  Interval: number;
}
/**
 * Конфигурация каналов управления подсветкой и освещением
 */
export interface LightConfig {
  /**
   * Отображение индекса секции или устройства на имя канала освещения
   */
  Channels: {
    /**
     * Имя канала управления подсветкой
     *
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^[0-9]+$".
     */
    [k: string]: string;
  };
}
/**
 * Конфигурация подсистемы электропитания
 */
export interface PowerConfig {
  Mains: MainsConfig;
  /**
   * Список источников питания (PSU)
   */
  PSU: PsuConfig[];
  /**
   * Список шин распределения электропитания
   */
  Bus: BusConfig[];
}
/**
 * Параметры электропитания сети переменного тока
 */
export interface MainsConfig {
  /**
   * Номинальное сетевое напряжение, В (по умолчанию 230)
   */
  Voltage: number;
  /**
   * Минимально допустимое сетевое напряжение, В (по умолчанию 170)
   */
  VoltageMin: number;
  /**
   * Максимально допустимое сетевое напряжение, В (по умолчанию 250)
   */
  VoltageMax: number;
  /**
   * Максимальная потребляемая мощность аппарата, Вт (по умолчанию 200)
   */
  PowerMax: number;
}
/**
 * Конфигурация источника питания (ИП / PSU)
 */
export interface PsuConfig {
  /**
   * Обозначение источника питания на монтажной схеме
   */
  RefDes: string;
  /**
   * Модель источника питания
   */
  Model: string;
  /**
   * Номер подключенной шины электропитания
   */
  Bus: number;
  /**
   * Входное напряжение, В (по умолчанию 230)
   */
  VoltageIn: number;
  /**
   * Выходное напряжение, В
   */
  VoltageOut: number;
  /**
   * Ограничение максимального выходного тока, А
   */
  CurrentMax: number;
  Battery?: BatteryConfig;
  Field: FieldRef;
  /**
   * Каналы мониторинга источника питания
   */
  Channels?: {
    /**
     * Имя канала входящего напряжения
     */
    VoltageIn?: string;
    /**
     * Имя канала выходящего напряжения
     */
    VoltageOut?: string;
    /**
     * Имя канала выходящего тока
     */
    CurrentOut?: string;
    /**
     * Имя канала мощности
     */
    Power?: string;
    /**
     * Имя канала температуры
     */
    Temp?: string;
  };
}
/**
 * Параметры резервной аккумуляторной батареи
 */
export interface BatteryConfig {
  /**
   * Модель батареи
   */
  Model: string;
  type: BATTERY_TYPE;
  /**
   * Номинальное напряжение батареи, В
   */
  Voltage: number;
  /**
   * Ёмкость батареи, Ач
   */
  Capacity: number;
}
/**
 * Ссылка на подключение устройства к полевой шине
 */
export interface FieldRef {
  /**
   * Ссылка на полевую шину (например, 'hubLow/PORT1', 'ICP-CON2/com1')
   */
  ref: string;
  /**
   * Адрес устройства на шине
   */
  ID: string;
}
/**
 * Конфигурация шины электропитания
 */
export interface BusConfig {
  /**
   * Флаг первичного сетевого ввода (true - сетевой ввод Mains, false - вторичная шина от источника)
   */
  source?: boolean;
  /**
   * Номинальное напряжение шины, В
   */
  Voltage: number | string;
  /**
   * Максимально допустимый ток шины, А
   */
  CurrentMax: number | string;
}
/**
 * Конфигурация подсистемы климатического контроля
 */
export interface EnvConfig {
  /**
   * Список датчиков температуры
   */
  Temp: TempSensorConfig[];
  /**
   * Список датчиков влажности
   */
  Hum: HumSensorConfig[];
}
/**
 * Конфигурация датчика температуры
 */
export interface TempSensorConfig {
  /**
   * Обозначение датчика температуры на монтажной схеме
   */
  RefDes: string;
  /**
   * Модель датчика температуры
   */
  Model: string;
  /**
   * Минимальная рабочая температура, °C (по умолчанию 0)
   */
  Min: number;
  /**
   * Максимальная рабочая температура, °C (по умолчанию 40)
   */
  Max: number;
  Field: FieldRef;
  /**
   * Каналы датчика температуры
   */
  Channels: {
    /**
     * Имя канала температуры
     */
    Temp: string;
  };
}
/**
 * Конфигурация датчика влажности
 */
export interface HumSensorConfig {
  /**
   * Обозначение датчика влажности на монтажной схеме
   */
  RefDes: string;
  /**
   * Модель датчика влажности
   */
  Model: string;
  /**
   * Минимальная рабочая влажность, % (по умолчанию 10)
   */
  Min: number;
  /**
   * Максимальная рабочая влажность, % (по умолчанию 80)
   */
  Max: number;
  Field: FieldRef;
  /**
   * Каналы датчика влажности
   */
  Channels: {
    /**
     * Имя канала влажности
     */
    Hum: string;
  };
}
/**
 * Сетевая конфигурация аппарата
 */
export interface NetConfig {
  /**
   * Общие сетевые параметры
   */
  Common: {
    /**
     * Сетевая маска (например, '255.255.255.0')
     */
    mask: string;
    /**
     * Сетевой шлюз
     */
    gw: string;
  };
  Router: RouterConfig;
  Switch: SwitchConfig;
  /**
   * IP-адреса управляющих микрокомпьютеров (хабов)
   */
  Hub: {
    Low: {
      IP: string;
      /**
       * Канал температуры процессора хаба
       */
      CpuTempChannel?: string;
    };
    Mid: {
      IP: string;
    };
    High: {
      IP: string;
    };
  };
  /**
   * Сетевые параметры серверного ПО и сервисов
   */
  SW: {
    LOW: {
      REDIS: {
        IP: string;
        PORT: string;
      };
    };
    MID: {
      MQTT: {
        IP: string;
        PORT: string;
        WS_PORT: string;
        CLIENT_URL: string;
      };
      MONGODB: {
        IP: string;
        PORT: string;
      };
      NTP: {
        IP: string;
        PORT: string;
      };
      GRAYLOG: {
        IP: string;
        WEB: {
          PORT: number;
        };
        INPUT: {
          PORT: number;
        }[];
        URL: string;
      };
    };
  };
}
/**
 * Конфигурация сетевого роутера
 */
export interface RouterConfig {
  /**
   * Обозначение роутера на монтажной схеме
   */
  RefDes: string;
  Power: NetPowerDeviceConfig;
  WAN: WanConfig;
  /**
   * Список портов роутера
   */
  port: NetPortConfig[];
}
/**
 * Параметры электропитания сетевого устройства
 */
export interface NetPowerDeviceConfig {
  /**
   * Номер шины электропитания
   */
  Bus: number;
  /**
   * Напряжение электропитания, В
   */
  Voltage: number;
  /**
   * Максимальный потребляемый ток, А
   */
  CurrentMax: number;
  /**
   * Мощность потребления, Вт
   */
  Power: number;
}
/**
 * Конфигурация внешнего сетевого интерфейса (WAN)
 */
export interface WanConfig {
  /**
   * Имя uplink-порта
   */
  name: string;
  mode: WAN_MODE;
  /**
   * IP-адрес (для static режима)
   */
  ip?: string;
  /**
   * Сетевая маска (для static режима)
   */
  mask?: string;
  /**
   * Шлюз (для static режима)
   */
  gw?: string;
  /**
   * Список IP-адресов DNS-серверов
   */
  dns?: string[];
}
/**
 * Параметры порта сетевого устройства
 */
export interface NetPortConfig {
  /**
   * Имя порта
   */
  name: string;
  /**
   * Флаг наличия/активности PoE
   */
  poe: boolean;
}
/**
 * Конфигурация сетевого коммутатора
 */
export interface SwitchConfig {
  /**
   * Обозначение коммутатора на монтажной схеме
   */
  RefDes: string;
  /**
   * Модель коммутатора
   */
  Model: string;
  /**
   * Общее количество портов коммутатора
   */
  PortsTotal: number;
  Power: NetPowerDeviceConfig;
}
/**
 * Конфигурация полевых шин (RS485, CAN, TCP)
 */
export interface FieldBusesConfig {
  /**
   * Список шин RS485
   */
  RS485: RS485BusConfig[];
  /**
   * Список шин CAN
   */
  CAN: CanBusConfig[];
  /**
   * Список шин MODBUS/TCP
   */
  TCP: TcpBusConfig[];
}
/**
 * Конфигурация полевой шины RS485 (MODBUS/RTU)
 */
export interface RS485BusConfig {
  /**
   * Обозначение шины на монтажной схеме
   */
  RefDes: string;
  /**
   * Мастер-устройство ('hubLow', 'icpcon1' и т.д.)
   */
  Master: string;
  /**
   * Имя порта на мастере или 'ip:port'
   */
  Port: string;
  /**
   * Скорость работы порта (бод)
   */
  Baud: number;
}
/**
 * Конфигурация полевой шины CAN
 */
export interface CanBusConfig {
  /**
   * Обозначение шины на монтажной схеме
   */
  RefDes: string;
}
/**
 * Конфигурация сетевой полевой шины MODBUS/TCP
 */
export interface TcpBusConfig {
  /**
   * Подсеть MODBUS/TCP
   */
  SubNet: string;
}
/**
 * Конфигурация модуля ввода/вывода (IO)
 */
export interface IoModuleConfig {
  /**
   * Обозначение модуля на монтажной схеме
   */
  RefDes: string;
  /**
   * Модель модуля IO
   */
  Model: string;
  Field: FieldRef;
  /**
   * Сетевые параметры IO модуля
   */
  Net?: {
    /**
     * IP-адрес модуля
     */
    IP: string;
    /**
     * Порт веб-интерфейса
     */
    Web: number;
  };
}
/**
 * Конфигурация IP-видеокамеры
 */
export interface CameraConfig {
  /**
   * Обозначение камеры на монтажной схеме
   */
  RefDes: string;
  /**
   * Модель камеры
   */
  Model: string;
  /**
   * Параметры объектива
   */
  Lens: {
    /**
     * Модель объектива
     */
    Model: string;
    /**
     * Начальная установка зума
     */
    Zoom: number;
  };
  /**
   * Стартовое панорамирование
   */
  Pan: number;
  /**
   * Начальная установка наклона
   */
  Tilt: number;
  /**
   * Сетевые параметры камеры
   */
  Net: {
    /**
     * IP-адрес камеры
     */
    IP: string;
    /**
     * RTP-порт видеопотока
     */
    RTP: number;
  };
}
/**
 * Конфигурация отдельной секции аппарата
 */
export interface SectionConfig {
  /**
   * Уникальное имя секции (например, 'spiral', 'postomat')
   */
  Name: string;
  /**
   * Идентификатор секции
   */
  ID: string;
  Type: SECTION_TYPE;
  /**
   * Число полок в секции
   */
  Rows: number;
  /**
   * Число ячеек на полке
   */
  Cols: number;
  /**
   * Номер подключенной шины электропитания
   */
  PowerBus: number;
  /**
   * Массив имён модулей ввода-вывода (IO), закреплённых за данной секцией
   */
  IOList: string[];
  Channels: SectionChannelsConfig;
  Lift?: SectionLiftConfig;
  Storage?: SectionStorageConfig;
  CellOpts?: SectionCellOptsConfig;
}
/**
 * Группа всех каналов ввода/вывода секции
 */
export interface SectionChannelsConfig {
  Door?: DoorChannelsConfig;
  DeliveryBox?: DeliveryBoxChannelsConfig;
  Storage?: StorageChannelsConfig;
  Lift?: LiftChannelsConfig;
  Led?: LedChannelsConfig;
}
/**
 * Канал концевика двери секции
 */
export interface DoorChannelsConfig {
  /**
   * Канал концевика двери
   */
  Sensor: string;
}
/**
 * Каналы отсека выдачи товара
 */
export interface DeliveryBoxChannelsConfig {
  /**
   * Канал замка / привода шторки отсека выдачи
   */
  Lock?: string;
  /**
   * Канал оптического датчика наличия / падения товара
   */
  Optic?: string;
  /**
   * Канал мониторинга отсека выдачи
   */
  Monitoring?: string;
}
/**
 * Каналы полок и ячеек секции
 */
export interface StorageChannelsConfig {
  /**
   * Канал управления матрицей ячеек
   */
  MatrixCtrl?: string;
  /**
   * Список каналов строк и колонок для матричного управления
   */
  Port?: string[];
  /**
   * Список каналов датчиков состояния ячеек
   */
  Tamper?: string[];
  /**
   * Канал мониторинга ячеек
   */
  Monitoring?: string;
}
/**
 * Каналы лифта выдачи товаров
 */
export interface LiftChannelsConfig {
  /**
   * Канал управления приводом лифта
   */
  MotorCtrl?: string;
  /**
   * Канал оптического датчика позиционирования уровня лифта
   */
  LevelSensor?: string;
  /**
   * Канал нижнего концевика лифта
   */
  BottomTamper?: string;
  /**
   * Канал верхнего концевика лифта
   */
  TopTamper?: string;
  /**
   * Канал мониторинга привода лифта
   */
  Monitoring?: string;
}
/**
 * Параметры механизма лифта
 */
export interface SectionLiftConfig {
  /**
   * Максимальный этаж/уровень лифта
   */
  MaxLevel: number;
}
/**
 * Параметры хранилища ячеек
 */
export interface SectionStorageConfig {
  /**
   * Шаблон имени канала датчиков ячеек
   */
  TamperPattern?: string;
}
/**
 * Параметры адресации строк и колонок ячеек
 */
export interface SectionCellOptsConfig {
  /**
   * Индексы каналов строк
   */
  Row: number[];
  /**
   * Индексы каналов колонок
   */
  Col: number[];
}

/**
 * Тип аккумулятора (lipo - литий-полимерный, lead - свинцово-кислотный)
 */
export enum BATTERY_TYPE {
  LIPO = "lipo",
  LEAD = "lead"
}
/**
 * Режим работы WAN-порта (static - статический IP, dhcp - динамический IP)
 */
export enum WAN_MODE {
  STATIC = "static",
  DHCP = "dhcp"
}
/**
 * Тип секции вендингового аппарата (POST - постомат, SPIRAL - спиральная секция, WEIGHT - весовая секция приёма лома, DOZER - диспенсер сыпучих/жидких материалов)
 */
export enum SECTION_TYPE {
  POST = "POST",
  SPIRAL = "SPIRAL",
  WEIGHT = "WEIGHT",
  DOZER = "DOZER"
}
